@alerts
Feature: Alerts
In order to demonstrate interactions with alerts
As a Calabash maintainer
I want some Scenarios that show Calabash working with alerts

# These are alerts that are presented by _your_ application using:
#
#   UIAlertView *alert = [[UIAlertView alloc] ...];
#   [alert show];
#
# These are _not_ alerts generated by the OS on behalf of your
# app.  Such alerts are also known as the "Privacy alerts".  You
# can read more about interacting with UIAlerts presented by the
# OS here:
#
# https://github.com/calabash/calabash-ios/wiki/Managing-Privacy-Alerts%3A--Location-Services%2C-APNS%2C-Contacts

Background: Navigate to the special tab
 Given I see the special tab

@animations
Scenario: Touch OK button on alert
  When I touch the show alert button
  Then I see an alert
  Then I see the "Smoke Test!" alert
  And I wait for all animations to stop
  And I can dismiss the alert with the OK button

Scenario: Verify the alert title, message, and buttons
  When I touch the show alert button
  Then I see an alert
  And the title of the alert is "Smoke Test!"
  And the message of the alert is "Another day, another iOS alert"
  And the left hand button is "Cancel"
  And the right hand button is "OK"

